name: ${project.name}
main: ${project.groupId}.${project.artifactId}.Main
version: ${project.version}
author: LeonTG77
description: All mobs are disguised as villagers.
softdepend: [ProtocolLib]

commands:
  xenophobia:
    description: Enable or disable the gamemode.
    aliases: [xenop]